name: Weekly Dev to Main and Main to Prod Sync

on:
  schedule:
    - cron: '0 12 * * 4'  # Every Thursday at 12 PM UTC
  workflow_dispatch:

jobs:
  sync:
    name: Weekly Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Check for recent commits
        id: check_changes
        run: |
          echo "Checking for recent changes..."

          DEV_COMMITS=$(git log origin/dev --since="7 days ago" --oneline | wc -l)
          MAIN_COMMITS=$(git log origin/main --since="7 days ago" --oneline | wc -l)

          echo "Dev commits in last 7 days: $DEV_COMMITS"
          echo "Main commits in last 7 days: $MAIN_COMMITS"

          echo "dev_changed=$([ "$DEV_COMMITS" -gt 0 ] && echo true || echo false)" >> $GITHUB_OUTPUT
          echo "main_changed=$([ "$MAIN_COMMITS" -gt 0 ] && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Push main to prod (if main changed)
        if: steps.check_changes.outputs.main_changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout main
          git pull origin main
          git push origin main:prod

      - name: Check if PR from dev to main already exists
        if: steps.check_changes.outputs.dev_changed == 'true'
        id: check_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:dev`,
              base: 'main'
            });

            const exists = prs.length > 0;
            core.setOutput('pr_exists', exists.toString());

      - name: Create PR from dev to main
        if: steps.check_changes.outputs.dev_changed == 'true' && steps.check_pr.outputs.pr_exists == 'false'
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: dev
          base: main
          title: '🔁 Automated weekly merge from dev to main'
          body: |
            This PR was created automatically to sync changes from `dev` to `main`.
          draft: false

      - name: Auto-merge PR
        if: steps.cpr.outputs.pull-request-url
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prUrl = "${{ steps.cpr.outputs.pull-request-url }}";
            const prNumber = prUrl.split('/').pop();

            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'merge'
            });

            console.log(`Merged PR #${prNumber} from dev to main`);
